version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
    volumes:
      - mysql_pub:/var/lib/mysql

  flask:
    container_name: flask
    image: yurcall/flask-api
    restart: on-failure:10
    env_file: .env
    environment:
      - DB_USERNAME=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_PASSWORD}
      - DB_HOSTNAME=mysql
      - DB_NAME=${MYSQLDB_DATABASE}
    depends_on:
      - mysql
    ports:
      - '5000:5000'

volumes:
  mysql_pub:
